accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.loginView, name ="loginView"),
    path("register/", views.registerView, name ="registerView"),
    path("loginform/", views.loginForm, name = "login"),
    path("registerform/", views.registerForm, name ="register"),
    path("logout/", views.logoutView, name ="logout")

]

api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("", views.get_messages, name = "index"),
    path("send/", views.send_message, name ="send")
]

chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("authentication/", include("accounts.urls")),
    path("api/", include("api.urls"))
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name ="index"),
    path("create/", views.create_room, name = "create_room"),
    path("room/<str:hash>/", views.room, name = "room"),
    path("join/", views.join_room, name = "join"),
    path("leave/<str:hash>", views.leave_room, name = "leave")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    friends = models.ManyToManyField('self')

core/models.py
from django.db import models

from accounts.models import User

from .utils import get_random_string

import hashlib


# Create your models here.

class Link(models.Model):
    linkTo = models.URLField(max_length=200)

class Room(models.Model):
    hash = models.CharField(max_length = 64, unique = True, default = None, null = True, blank = True)
    title = models.CharField(max_length = 256)
    users = models.ManyToManyField(User, related_name = "rooms")
    link = models.ForeignKey(Link, related_name = "link", on_delete = models.PROTECT, null = True, blank = True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.hash is None:
            raw_hash = get_random_string()
            encoded_raw_hash = raw_hash.encode()
            self.hash = hashlib.sha256(encoded_raw_hash).hexdigest()
        super().save(*args, **kwargs)  # Call the "real" save() method.

class Message(models.Model):
    room = models.ForeignKey(Room, related_name = "messages" ,on_delete = models.CASCADE)
    sender = models.ForeignKey(User, related_name= "sent", on_delete = models.CASCADE)
    text = models.CharField(max_length=  256)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"message in {self.room}"

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from .models import User
# Create your views here.

def loginView(request):
    return render(request, "accounts/login.html")

def registerView(request):
    return render(request, "accounts/register.html")

def loginForm(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        print("sdfsdf")
        user = authenticate(username = username, password = password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("core:index"))
        messages.error(request, "Invalid login")
        return render(request, "accounts/login.html")

def registerForm(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        confirm_password = request.POST["confirmpassword"]

        if password != confirm_password:
            messages.error(request, "Passwords don't match!")
            return render(request, "accounts/register.html")
        
        user = authenticate(username = username, password = password)
        if user is not None:
            messages.error(request, "User already exists!")
            return render(request, "accounts/register.html")
        else:
            user = User.objects.create_user(username = username, password = password)
            user.save()
            login(request,user)
            return HttpResponseRedirect(reverse("core:index"))
        
def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse("accounts:loginView"))

api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from . import serializers
from core.models import Message
import accounts


#APIs FOR MESSAGES

@api_view(['GET'])
def get_messages(request):
    messages = Message.objects.all()
    serializer = serializers.MessageSerializer(messages, many = True)
    return Response(serializer.data)

@api_view(['GET'])
def get_messages_chat(request, id):
    pass

@api_view(['POST'])
def send_message(request):
    serializer = serializers.MessageSerializer(data = request.data) 
    if serializer.is_valid():
        print(serializer.errors)
        serializer.save()
        return Response("Successfully saved!")
    print(serializer.errors)
    return Response("Something went wrong")

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from accounts.models import User
from .models import Room,Message

@login_required
def index(request):
    currentUser = request.user
    rooms = currentUser.rooms.all()
    context = {"rooms":rooms}
    return render(request, "core/index.html", context)

@login_required
def create_room(request):
    if request.method == "POST":
        title = request.POST["title"]
        room = Room(title = title)
        room.save()
        room.users.add(request.user)
        return HttpResponseRedirect(reverse("core:room", kwargs = {"hash" : room.hash}))
    return render(request, "core/create-room.html")

@login_required
def room(request, hash):
    room = Room.objects.get(hash = hash)
    room_messages = room.messages.all()
    context = {"room":room, "messages":room_messages}
    return render(request, "core/room.html", context)

@login_required
def join_room(request):
    hash = request.GET["room-hash"]
    room = Room.objects.get(hash = hash)

    if not request.user in room.users.all():
        room.users.add(request.user)
        room.save()
        return HttpResponseRedirect(reverse("core:room", kwargs = {"hash":room.hash}))
    
    return HttpResponseRedirect(reverse("core:room", kwargs = {"hash":room.hash}))

@login_required
def leave_room(request, hash):
    room = Room.objects.get(hash = hash)
    room.users.remove(request.user)
    return HttpResponseRedirect(reverse("core:index"))

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login Page</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4"><a href="{% url 'accounts:registerView' %}"></a>Have an account?</h3>

					<form method = "POST" action="{% url 'accounts:login' %}" class="login-form" >
						{% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" class="form-control rounded-left" placeholder="Username" name = "username" required>
		      		</div>
	            <div class="form-group d-flex">
	              <input type="password" class="form-control rounded-left" placeholder="Password" name = "password" required>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
								</div>
								<div class="w-50 text-md-right">
									<a href="{% url 'accounts:registerView' %}">Have no account?</a>
								</div>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="btn btn-primary rounded submit p-3 px-5">Get Started</button>
	            </div>
	          </form>
			  {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
	        </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'accounts/js/jquery.min.js'%}"></script>
  <script src="{% static 'accounts/js/popper.js'%}"></script>
  <script src="{% static 'accounts/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'accounts/js/main.js'%}"></script>

	</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
  	<title>Register</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Register Page</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4">Have an account?</h3>
				  <form method = "POST" action="{% url 'accounts:register' %}" class="login-form" >
					{% csrf_token %}
				  <div class="form-group">
					  <input type="text" class="form-control rounded-left" placeholder="Username" name = "username" required>
				  </div>
				<div class="form-group d-flex">
				<input type="password" class="form-control rounded-left" placeholder="Password" name = "password" required>
				</div>
				<div class="form-group d-flex">
					<input type="password" class="form-control rounded-left" placeholder="Password" name = "confirmpassword" required>
					</div>
			<div class="form-group d-md-flex">
				<div class="w-50">
							</div>
							<div class="w-50 text-md-right">
								<a href="#">Forgot Password?</a>
							</div>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary rounded submit p-3 px-5">Get Started</button>
			</div>
		  </form>
		  {% if messages %}
<ul class="messages">
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
{% endfor %}
</ul>
{% endif %}
	        </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'accounts/js/jquery.min.js'%}"></script>
  <script src="{% static 'accounts/js/popper.js'%}"></script>
  <script src="{% static 'accounts/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'accounts/js/main.js'%}"></script>

	</body>
</html>

core/templates/core/create-room.html
{% extends "core/layout.html" %}

{% block body %}

<div class = "p-10 lg:p-20 text-center">
    <h1 class = "text-3xl lg:text-6xl text-white">Create Chat</h1>
    <div class="mt-4">
        <div class="">
            <form action="{% url "core:create_room" %}" method = "POST">    
                {% csrf_token %}    
                <input type="text" class="flex-3 mr-3" name = "title">
                <button type="submit" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 input-field-button">Create</button>
            </form>
        </div>
    </div>

</div>

{% endblock body %}

core/templates/core/index.html
{% extends 'core/layout.html' %}

{% block body %}
<div class = "p-10 lg:p-20 text-center">
    <h1 class = "text-3xl lg:text-6xl text-white">Django Chat</h1>
    <div class="mt-4">
        <div class="">
            <form action="{% url 'core:join' %}" method = "GET">        
                <input type="text" name = "room-hash" class="flex-3 mr-3">
                <button type="submit" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 input-field-button">Join</button>
            </form>
        </div>
    </div>

    <h1 class = "text-3xl lg:text-6xl text-white">Your Rooms</h1>
    {% for room in rooms %}
    <div>
        
        <div>{{room.title}}</div>
        <a href="{% url "core:room" room.hash %}">
            <div class="p-4 bg-gray-200 rounded-xl">
            Click here!
            </div>
        </a>
        
    </div>
    
    {% endfor %}
        

</div>
{% endblock body %}

core/templates/core/layout.html
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <script src="{% static 'core/js/tailwind.js' %}"></script>
        <link rel="stylesheet" href="{% static "core/css/style.css" %}">
        {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> {% endcomment %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Django Real Time Application</title>
        <style>

            /* Input field */
    .input-field {
    width: 100%;
    padding: 1rem;
    border: 1px solid #ccc;
    border-radius: 0.5rem;
    display: flex;
    align-items: center;
    }

    /* Button inside input field */
    .input-field-button {
    background-color: #000;
    color: #fff;
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 0.5rem;
    cursor: pointer;
    }

    /* Position the button inside the input field */
    .input-field .input-field-button {
    position: absolute;
    right: 1rem;
    top: 0.5rem;
    }
            nav{
                height:70px;
            }

        </style>
    </head>
    <body class = "bg-teal-600">
        <nav class ="flex items-center justify-between px-4 px-6 bg-teal-800">
            <div>
                <a href="{% url 'core:index' %}" class = "text-xl text-white">Django Real Time Application</a>
            </div>

            <div class="flex item-center space-x-4">
                <a href="{% url 'core:create_room' %}" class = "text-white hover:text-gray-200">Create New Chat</a>
            </div>

            <div class="flex item-center space-x-4">
                <a href="{% url 'accounts:logout' %}" class = "text-white hover:text-gray-200">Log Out</a>
            </div>

            <div class="flex item-center space-x-4">
                {% block leave %}
                {% endblock leave %}
            </div>
           

           
        
        </nav>

        {% block body %}

        {% endblock body %}

        {% block scripts %}{% endblock scripts %}

    </body>
    </html>

core/templates/core/room.html
{% extends 'core/layout.html' %}

{% block leave %}

<a href="{% url 'core:leave' room.hash %}">Leave Chat</a>

{% endblock leave %}




{% block body %}
<div class = "p-10 lg:p-20 text-center">

    <h1 class = "text-3xl lg:text-6xl text-white">{{room.title}}</h1>
    {% if  request.user in room.users.all %}
    <div class="lg:w-2/4 mx-4 lg:max-auto p-4 bg-white rounded-xl content-center">

        <div class="chat-messages space-y-3" id = "chat-messages">
            {% for message in messages %}
            <div class="p-4 bg-gray-200 rounded-xl">
                <p class = "font-semibold">{{message.sender}}</p>
                <p>{{message.text}}</p>
            </div>
            {% endfor %}
    
        </div>
    
    </div>

    <div class="lg:w-2/4 mt-6 mx-4 lg:max-auto p-4 bg-white rounded-xl">
        <form action="" class ="flex" id = "form" method = "POST">      
            {% csrf_token %}  
            <input type="text" class="flex-3 mr-3" id = "message">
            <button type="submit" class="inline-flex items-center 
            px-3 py-2 border border-transparent text-sm 
            leading-4 font-medium rounded-md text-white 
            bg-indigo-600 hover:bg-indigo-700 
            focus:outline-none focus:ring-2 
            focus:ring-offset-2 focus:ring-indigo-500 
            input-field-button" id = "submit-button">Send</button>
        </form>
    </div>
    {%else%}
        <h2>You are not in this group!</h2>
    {% endif %}
    

</div>



{% endblock body %}

{% block scripts %}
{{room.hash|json_script:"json-roomhash"}}
{{request.user.username|json_script:"json-username"}}
<script type = "text/javascript">
   
    const room_hash = JSON.parse(document.getElementById("json-roomhash").textContent)
    const username = JSON.parse(document.getElementById("json-username").textContent)

    let url = `ws://${window.location.host}/ws/${room_hash}/`

    const chatSocket = new WebSocket(url)

    chatSocket.onmessage = function(e){

        const data = JSON.parse(e.data)

        if(data.message){
            let html = '<div class="p-4 bg-gray-200 rounded-xl">'
                html += `<p class = "font-semibold">${data.username}</p>`
                html+=`<p>${data.message}</p>`
                html += '</div>'

                document.querySelector("#chat-messages").innerHTML +=html
        }
        else{
            alert("not message")
        }

    }

    chatSocket.onclose = function(e){
        console.log("closed")
    }

    const form = document.querySelector("#form")
    const submit_button = document.querySelector("#submit-button")

    form.addEventListener('submit', (e)=>{
        e.preventDefault()
        let message =  e.target.message.value
        chatSocket.send(JSON.stringify({
            'type':'message',
            'message':message,
            'username': username,
            'room_hash':room_hash
        }))
        form.reset()
    })

</script>
{% endblock scripts %}